[category:cover]
image-noise=true
title-shadow=true
title-color=light
image-shadow=true
title-visible=true
image-card-border=false
empty-card-border=true

[brand]
name=Nebula
logo=data/icons/brand/logo.svg
favicon=data/icons/brand/favicon.svg

[post:light-theme]
subtitle-color=#987733

[post:dark-theme]
subtitle-color=#86703C
