[Brand]
name=Nebula
logo=data/icons/brand/logo.svg
favicon=data/icons/brand/favicon.svg
display_logo=True
display_name=False

[Post:LightTheme]
subtitle_color=#987733

[Post:DarkTheme]
subtitle_color=#86703C
