[Category:Cover]
noise=true
title-shadow=true
title-color=light
shadow=true
display-title=true

[Brand]
name=Nebula
logo=data/icons/brand/logo.svg
favicon=data/icons/brand/favicon.svg

[Post:LightTheme]
subtitle-color=#987733

[Post:DarkTheme]
subtitle-color=#86703C
